language: generic
sudo: required
services:
- docker
script:
- docker run -v $(pwd):$(pwd) -t ubuntu:yakkety sh -c "cd $(pwd) && .travis/build.sh armhf"
before_deploy:
- .travis/decrypt.sh
deploy:
- provider: releases
  skip_cleanup: true
  file: "*.snap"
  file_glob: true
  api_key:
    secure: AGF5VzQtQab4TZay3pXH1AnovhgS9hjOn26ZZut3s6LlIdgDMysSHs42ymiJAHvFykgk47S5IfHzhXDGgRYBD1Jg9dNMDzIo59mzSbcPanV3dw+uG5HbnrZpVE8JMxWTgwU4YRdfEXdXo/Zio7we/zUAtFPciC93rc+CdvOKkzB0b8ux2gSxMONFpRT0G4t9OcVukgYhp/nO/WtifpHQ8xDlHGdIiiUBw1qn0+CM7Xc3SsY/6RwmJhREG/LP07cq0RYpJTqcnUMLE8ZvePR2QXRIIrZaNlgVZJ0s66wu2kF7qzWxjtDHOr1Sa/r2ezIxHJbRMPW5boXlvY0SHc2UXHI1SunBR2or2lv6lM29UEAAmSkkfKVjBE4yXbpesVO4bmCnD9SbdcwWt9LvW5nkUeDZPvC3n4Pc9ByA46SxdXgqOj24f6p3ghdwXOaColJIDN6TBaTB9yRML+/qfRqDfQtM0EcVmw+aEYkbZXArAb9IwUvV0WsWdvYkA785xmEUWbQ16RKDsMDDLCPntMouSvOWKFkkfuy2LUifcYsIAq8p0os1Vt+1AkalvdoEbgDREvSI2/iw1czOq9C8KZ2mT6bsbk5YpR3Na5qB4GBtcm6zKn7uhXnkn3Pm/CyWUwNAFCi58S+8iq2C/YfTAbOIG2xASmD6n/Nq1h4DP4ZfIc8=
  on:
    repo: fuzeman/nanopi-neo-kernel
    tags: true
- provider: script
  skip_cleanup: true
  script:
  - docker run -v $(pwd):$(pwd) -t ubuntu:yakkety sh -c "cd $(pwd) && .travis/push.sh $TRAVIS_TAG"
  on:
    repo: fuzeman/nanopi-neo-kernel
    tags: true
#- provider: script
#  skip_cleanup: true
#  script:
#  - docker run -v $(pwd):$(pwd) -t ubuntu:yakkety sh -c "cd $(pwd) && .travis/push.sh"
#  on:
#    repo: fuzeman/nanopi-neo-kernel
#    branch: master
