name: nanopi-neo-kernel
summary: Minimal kernel for the NanoPi NEO
version: 4.10.0-2001.2-beta.2
type: kernel

description: |
  Kernel for the NanoPi NEO with the bare minimum drivers and modules.

  See https://github.com/fuzeman/nanopi-neo-kernel for details.

architectures: [armhf]
confinement: devmode
grade: devel

parts:
    kernel:
        plugin: fm-kernel

        source: https://github.com/fuzeman/linux-ubuntu-zesty.git
        source-tag: Ubuntu-sunxi-4.10.0-2001.2
        source-depth: 1
        source-type: git

        build-packages:
          - bc
          - cpio
          - kmod
          - libc6-dev
          - libssl-dev

        kdefconfig: ['--makefile=debian/snapcraft.mk', 'branch=sunxi','flavour=nanopi-neo', 'config']
        kernel-image-target: zImage

        fm-kernel-flavour: nanopi-neo
        fm-kernel-version: 4.10.0-2001.2

        kconfigs:
          - CONFIG_SQUASHFS=m
          - CONFIG_DEVPTS_MULTIPLE_INSTANCES=y

        kernel-initrd-modules:
          - squashfs

        kernel-device-trees:
          - sun8i-h3-nanopi-neo

        prepare: |
          touch .scmversion
